export * from "./detalhes-header";
export * from "./detalhes-kpis";
export * from "./detalhes-tabs-nav";
export * from "./tab-alunos";
export * from "./tab-sessoes";
export * from "./tab-espaco";
export * from "./matricular-aluno-modal";
export * from "./detalhes-skeleton";
export * from "./detalhes-not-found";
